<a href="https://colab.research.google.com/github/Joeaviator/SUBQUERY-SQLITE/blob/main/SubQuery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
file=files.upload()

Saving database.sqlite to database.sqlite

In [2]:
import numpy as np
import pandas as pd
import sqlite3

In [3]:
database='database.sqlite'
conne=sqlite3.connect(database)
print("Database connected successfully")

Database connected successfully

In [4]:
#Read the tables
tables=pd.read_sql("""SELECT * FROM sqlite_master WHERE type='table'""",conne)
tables

,type,name,tbl_name,rootpage,sql
0,table,Player,Player,2,CREATE TABLE [Player] (\n\t[Player_Id]\tintege...
1,table,Extra_Runs,Extra_Runs,3,CREATE TABLE [Extra_Runs] (\n\t[Match_Id]\tint...
2,table,Batsman_Scored,Batsman_Scored,7,CREATE TABLE [Batsman_Scored] (\n\t[Match_Id]\...
3,table,Batting_Style,Batting_Style,10,CREATE TABLE [Batting_Style] (\n\t[Batting_Id]...
4,table,Bowling_Style,Bowling_Style,11,CREATE TABLE [Bowling_Style] (\n\t[Bowling_Id]...
5,table,Country,Country,12,CREATE TABLE [Country] (\n\t[Country_Id]\tinte...
6,table,Season,Season,14,CREATE TABLE [Season] (\n\t[Season_Id]\tintege...
7,table,City,City,15,CREATE TABLE [City] (\n\t[City_Id]\tinteger NO...
8,table,Outcome,Outcome,16,CREATE TABLE [Outcome] (\n\t[Outcome_Id]\tinte...
9,table,Win_By,Win_By,17,CREATE TABLE [Win_By] (\n\t[Win_Id]\tinteger N...
10,table,Wicket_Taken,Wicket_Taken,18,CREATE TABLE [Wicket_Taken] (\n\t[Match_Id]\ti...
11,table,Venue,Venue,21,CREATE TABLE [Venue] (\n\t[Venue_Id]\tinteger ...
12,table,Extra_Type,Extra_Type,23,CREATE TABLE [Extra_Type] (\n\t[Extra_Id]\tint...
13,table,Out_Type,Out_Type,24,CREATE TABLE [Out_Type] (\n\t[Out_Id]\tinteger...
14,table,Toss_Decision,Toss_Decision,25,CREATE TABLE [Toss_Decision] (\n\t[Toss_Id]\ti...
15,table,Umpire,Umpire,26,CREATE TABLE [Umpire] (\n\t[Umpire_Id]\tintege...
16,table,Team,Team,27,CREATE TABLE [Team] (\n\t[Team_Id]\tinteger NO...
17,table,Ball_by_Ball,Ball_by_Ball,28,CREATE TABLE [Ball_by_Ball] (\n\t[Match_Id]\ti...
18,table,sysdiagrams,sysdiagrams,31,CREATE TABLE [sysdiagrams] (\n\t[name]\tnvarch...
19,table,sqlite_sequence,sqlite_sequence,32,"CREATE TABLE sqlite_sequence(name,seq)"
20,table,Match,Match,34,CREATE TABLE [Match] (\n\t[Match_Id]\tinteger ...
21,table,Rolee,Rolee,36,CREATE TABLE [Rolee] (\n\t[Role_Id]\tinteger N...
22,table,Player_Match,Player_Match,37,CREATE TABLE [Player_Match] (\n\t[Match_Id]\ti...

In [6]:
team= pd.read_sql("""SELECT * FROM Team""",conne)
team

    Team_Id                    Team_Name
0         1        Kolkata Knight Riders
1         2  Royal Challengers Bangalore
2         3          Chennai Super Kings
3         4              Kings XI Punjab
4         5             Rajasthan Royals
5         6             Delhi Daredevils
6         7               Mumbai Indians
7         8              Deccan Chargers
8         9         Kochi Tuskers Kerala
9        10                Pune Warriors
10       11          Sunrisers Hyderabad
11       12      Rising Pune Supergiants
12       13                Gujarat Lions

In [7]:
season=pd.read_sql("""SELECT * FROM Season;""",conne)
season

   Season_Id  Man_of_the_Series  Orange_Cap  Purple_Cap  Season_Year
0          1                 32         100         102         2008
1          2                 53          18          61         2009
2          3                133         133         131         2010
3          4                162         162         194         2011
4          5                315         162         190         2012
5          6                 32          19          71         2013
6          7                305          46         364         2014
7          8                334         187          71         2015
8          9                  8           8         299         2016

In [10]:
matches=pd.read_sql("""SELECT * FROM Match;""",conne)
matches

,Match_Id,Team_1,Team_2,Match_Date,Season_Id,Venue_Id,Toss_Winner,Toss_Decide,Win_Type,Win_Margin,Outcome_type,Match_Winner,Man_of_the_Match
0,335987,2,1,2008-04-18 00:00:00,1,1,2,1,1,140.0,1,1.0,2.0
1,335988,4,3,2008-04-19 00:00:00,1,2,3,2,1,33.0,1,3.0,19.0
2,335989,6,5,2008-04-19 00:00:00,1,3,5,2,2,9.0,1,6.0,90.0
3,335990,7,2,2008-04-20 00:00:00,1,4,7,2,2,5.0,1,2.0,11.0
4,335991,1,8,2008-04-20 00:00:00,1,5,8,2,2,5.0,1,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
572,981016,6,2,2016-05-22 00:00:00,9,27,2,1,2,6.0,1,2.0,8.0
573,981018,13,2,2016-05-24 00:00:00,9,1,2,1,2,4.0,1,2.0,110.0
574,981020,11,1,2016-05-25 00:00:00,9,3,1,1,1,22.0,1,11.0,163.0
575,981022,13,11,2016-05-27 00:00:00,9,3,11,1,2,4.0,1,11.0,187.0
576,981024,2,11,2016-05-29 00:00:00,9,1,11,2,1,8.0,1,11.0,385.0

In [18]:
#Matches payed by RCB in 2016
RCB_Mattches=pd.read_sql("""
SELECT Match_Id,Team_2 As Away_Team, Toss_Winner, Match_Winner
FROM Match
WHERE Team_1= (SELECT Team_1 FROM Match WHERE Team_1==2 AND Season_Id==9);""",conne )
print("Matches played by Royal Challengers Bengaluru in 2016 are: ")
RCB_Mattches

Matches played by Royal Challengers Bengaluru in 2016 are:

    Match_Id  Away_Team  Toss_Winner  Match_Winner
0     335987          1            2           1.0
1     335997          5            5           5.0
2     336001          3            3           3.0
3     336011          4            4           4.0
4     336017          7            7           7.0
..       ...        ...          ...           ...
73    980974         12            2           2.0
74    980986          7            7           7.0
75    980992         13           13           2.0
76    981004          4            4           2.0
77    981024         11           11          11.0

[78 rows x 4 columns]

In [19]:
#Matches won by RCB
RCB_Won_Matches=pd.read_sql("""SELECT * FROM Match
WHERE Match_Winner==2 AND Season_Id=8;""", conne)
print("Matches won by RCB In 2016: ")
RCB_Won_Matches

Matches won by RCB In 2016:

,Match_Id,Team_1,Team_2,Match_Date,Season_Id,Venue_Id,Toss_Winner,Toss_Decide,Win_Type,Win_Margin,Outcome_type,Match_Winner,Man_of_the_Match
0,829718,1,2,2015-04-11 00:00:00,8,5,2,1,2,3,1,2,162
1,829754,5,2,2015-04-24 00:00:00,8,19,2,1,2,9,1,2,378
2,829762,6,2,2015-04-26 00:00:00,8,3,2,1,2,10,1,2,296
3,829776,2,1,2015-05-02 00:00:00,8,1,2,1,2,7,1,2,236
4,829790,2,4,2015-05-06 00:00:00,8,1,4,1,1,138,1,2,162
5,829800,7,2,2015-05-10 00:00:00,8,4,2,2,1,39,1,2,110
6,829812,11,2,2015-05-15 00:00:00,8,7,11,2,2,6,1,2,8
7,829824,2,5,2015-05-20 00:00:00,8,32,2,2,1,71,1,2,110

In [21]:
#Who was the match_winner in  a season, teams that played
match_winners=pd.read_sql("""SELECT m.Match_Id,
t1.Team_Name AS Team_1,
t2.Team_Name AS Team_2,
t3.Team_Name AS Match_Winner
FROM Match m
JOIN Team t1 ON m.Team_1=t1.Team_Id
JOIN Team t2 ON m.Team_2=t2.Team_Id
JOIN Team t3 ON m.Match_Winner=t3.Team_Id
WHERE m.Season_Id=8;""",conne)
match_winners

,Match_Id,Team_1,Team_2,Match_Winner
0,829710,Kolkata Knight Riders,Mumbai Indians,Kolkata Knight Riders
1,829712,Chennai Super Kings,Delhi Daredevils,Chennai Super Kings
2,829714,Kings XI Punjab,Rajasthan Royals,Rajasthan Royals
3,829716,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings
4,829718,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore
5,829720,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals
6,829722,Mumbai Indians,Kings XI Punjab,Kings XI Punjab
7,829724,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad
8,829726,Rajasthan Royals,Mumbai Indians,Rajasthan Royals
9,829728,Kolkata Knight Riders,Chennai Super Kings,Kolkata Knight Riders
10,829730,Kings XI Punjab,Delhi Daredevils,Delhi Daredevils
11,829732,Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals
12,829734,Mumbai Indians,Chennai Super Kings,Chennai Super Kings
13,829736,Sunrisers Hyderabad,Delhi Daredevils,Delhi Daredevils
14,829738,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders
15,829740,Rajasthan Royals,Chennai Super Kings,Rajasthan Royals
16,829742,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians
17,829744,Delhi Daredevils,Kolkata Knight Riders,Kolkata Knight Riders
18,829746,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab
19,829748,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad
20,829750,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings
21,829752,Delhi Daredevils,Mumbai Indians,Delhi Daredevils
22,829754,Rajasthan Royals,Royal Challengers Bangalore,Royal Challengers Bangalore
23,829756,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians
24,829758,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings
25,829762,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore
26,829764,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad
27,829766,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders
28,829770,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings
29,829772,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils
30,829774,Mumbai Indians,Rajasthan Royals,Mumbai Indians
31,829776,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore
32,829778,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad
33,829780,Kings XI Punjab,Mumbai Indians,Mumbai Indians
34,829782,Rajasthan Royals,Delhi Daredevils,Rajasthan Royals
35,829784,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings
36,829786,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata Knight Riders
37,829788,Mumbai Indians,Delhi Daredevils,Mumbai Indians
38,829790,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore
39,829792,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad
40,829794,Chennai Super Kings,Mumbai Indians,Mumbai Indians
41,829796,Kolkata Knight Riders,Kings XI Punjab,Kolkata Knight Riders
42,829798,Delhi Daredevils,Sunrisers Hyderabad,Sunrisers Hyderabad
43,829800,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore
44,829802,Chennai Super Kings,Rajasthan Royals,Chennai Super Kings
45,829804,Sunrisers Hyderabad,Kings XI Punjab,Sunrisers Hyderabad
46,829806,Delhi Daredevils,Chennai Super Kings,Delhi Daredevils
47,829808,Kings XI Punjab,Royal Challengers Bangalore,Kings XI Punjab
48,829810,Mumbai Indians,Kolkata Knight Riders,Mumbai Indians
49,829812,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore
50,829814,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings
51,829816,Rajasthan Royals,Kolkata Knight Riders,Rajasthan Royals
52,829820,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians
53,829822,Chennai Super Kings,Mumbai Indians,Mumbai Indians
54,829824,Royal Challengers Bangalore,Rajasthan Royals,Royal Challengers Bangalore
55,829826,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings
56,829828,Mumbai Indians,Chennai Super Kings,Mumbai Indians

In [24]:
#Man of the match compared to whether the team won the match
MOM=pd.read_sql("""
SELECT
 Match_Id, Team_1, Team_2, Match_Winner, Man_Of_The_Match
  FROM Match WHERE Match_Winner=Man_Of_the_Match;""", conne )
MOM

   Match_Id  Team_1  Team_2  Match_Winner  Man_of_the_Match
0    336015       1       2             1                 1
1    336019       8       1             1                 1
2    419140       1       8             1                 1
3    419149       1       6             1                 1
4    548371       4       8             4                 4